# Generated by Django 3.2 on 2021-04-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0002_auto_20210414_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonspecies',
            name='show_types',
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='pokemon_types',
            field=models.ManyToManyField(to='identify.PokemonTypes'),
        ),
    ]
