# Generated by Django 3.2 on 2021-04-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0003_auto_20210415_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
