# Generated by Django 3.2 on 2021-04-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0005_rename_pokemons_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='evolution_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
